# Generated by Django 5.2.12 on 2026-03-12 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='Used in the news URL. Generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('language', models.CharField(blank=True, choices=[('et', 'Estonian'), ('ru', 'Russian')], help_text='Leave empty to show this post for all languages.', max_length=7, null=True, verbose_name='language')),
                ('excerpt', models.TextField(blank=True, help_text='Optional short text shown in the news list.', verbose_name='short summary')),
                ('content', models.TextField(help_text='Main text of the news post. You can paste formatted text.', verbose_name='content (HTML allowed)')),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('is_featured', models.BooleanField(default=False, help_text='If enabled, this post will be highlighted on the home page for its language.', verbose_name='show on home page')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='published at')),
            ],
            options={
                'verbose_name': 'news post',
                'verbose_name_plural': 'news posts',
                'ordering': ('-published_at', '-created_at'),
            },
        ),
    ]
