# Generated by Django 5.2.12 on 2026-03-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', models.SlugField(help_text='Used in the course URL. Generated from title.', max_length=255, unique=True, verbose_name='slug')),
                ('language', models.CharField(blank=True, choices=[('et', 'Estonian'), ('ru', 'Russian')], help_text='Leave empty to show this course for all languages.', max_length=7, null=True, verbose_name='language')),
                ('short_description', models.TextField(blank=True, help_text='Short intro text shown in the courses list.', verbose_name='short summary')),
                ('age_range', models.CharField(blank=True, help_text='Example: 6–8 aastat', max_length=255, verbose_name='age range')),
                ('schedule', models.CharField(blank=True, help_text='Example: kord nädalas 90 min', max_length=255, verbose_name='schedule')),
                ('locations', models.TextField(blank=True, help_text='Where the course takes place.', verbose_name='locations')),
                ('content', models.TextField(help_text='Full description of the course. You can paste formatted text.', verbose_name='content (HTML allowed)')),
                ('image_url', models.URLField(blank=True, help_text='Optional image URL to show on the course page.', verbose_name='image URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower values appear first in the list.', verbose_name='order')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('order', 'title'),
            },
        ),
    ]
