# Generated by Django 5.2.12 on 2026-03-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_course_image_url_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional link to a course video (YouTube, Vimeo, etc.).', verbose_name='video URL'),
        ),
    ]
