# Generated by Django 5.2.12 on 2026-03-12 17:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_course_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Full description of the course. You can paste formatted text.', verbose_name='content (HTML allowed)'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Main text of the news post. You can paste formatted text.', verbose_name='content (HTML allowed)'),
        ),
    ]
