# Generated by Django 5.2.12 on 2026-03-12 17:33

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_course_content_alter_post_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ('order', 'slug'), 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
        migrations.RemoveField(
            model_name='course',
            name='age_range',
        ),
        migrations.RemoveField(
            model_name='course',
            name='content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='language',
        ),
        migrations.RemoveField(
            model_name='course',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='course',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='excerpt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='language',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
        migrations.CreateModel(
            name='CourseTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('et', 'Estonian'), ('ru', 'Russian')], max_length=7, verbose_name='language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('short_description', models.TextField(blank=True, help_text='Short intro text shown in the courses list.', verbose_name='short summary')),
                ('age_range', models.CharField(blank=True, help_text='Example: 6–8 aastat', max_length=255, verbose_name='age range')),
                ('schedule', models.CharField(blank=True, help_text='Example: kord nädalas 90 min', max_length=255, verbose_name='schedule')),
                ('locations', models.TextField(blank=True, help_text='Where the course takes place.', verbose_name='locations')),
                ('content', ckeditor.fields.RichTextField(help_text='Full description of the course. You can paste formatted text.', verbose_name='content (HTML allowed)')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.course', verbose_name='course')),
            ],
            options={
                'verbose_name': 'course translation',
                'verbose_name_plural': 'course translations',
                'unique_together': {('course', 'language')},
            },
        ),
        migrations.CreateModel(
            name='PostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('et', 'Estonian'), ('ru', 'Russian')], max_length=7, verbose_name='language')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('excerpt', models.TextField(blank=True, help_text='Optional short text shown in the news list.', verbose_name='short summary')),
                ('content', ckeditor.fields.RichTextField(help_text='Main text of the news post. You can paste formatted text.', verbose_name='content (HTML allowed)')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.post', verbose_name='post')),
            ],
            options={
                'verbose_name': 'news post translation',
                'verbose_name_plural': 'news post translations',
                'unique_together': {('post', 'language')},
            },
        ),
    ]
